### ISSUE TITLE
\Hyperf\Utils\Coroutine::sleep(1)方法

### ISSUE THREAD

**Issue by windhoney** [hyperf/utils#1]
[文档](https://doc.hyperf.io/#/zh/coroutine?id=parallel-%e7%89%b9%e6%80%a7)中使用
\Hyperf\Utils\Coroutine::sleep(1);
组件中并没有
应该直接用原生的\Swoole\Coroutine::sleep()？

**Comment by huangzhhui** [comment]
是可以执行的，`Hyperf\Utils\Coroutine` 里有个 `__callStatic` 的魔术方法，只是 IDE 没有提醒而已，事实上这里使用 `sleep()` `Hyperf\Utils\Coroutine::sleep()` `Swoole\Coroutine::sleep()` 都是可以的
