### ISSUE TITLE
php 8.1.0 有很多 return type 问题

### ISSUE THREAD

**Issue by lonze258** [hyperf/utils#4]
> PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1417

Deprecated: Return type of Hyperf\Utils\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1417
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1426

Deprecated: Return type of Hyperf\Utils\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1426
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1436

Deprecated: Return type of Hyperf\Utils\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1436
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1450

Deprecated: Return type of Hyperf\Utils\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Collection.php on line 1450
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 165

Deprecated: Return type of Hyperf\Utils\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 165
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 175

Deprecated: Return type of Hyperf\Utils\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 175
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 186

Deprecated: Return type of Hyperf\Utils\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 186
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 196

Deprecated: Return type of Hyperf\Utils\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 196
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 143

Deprecated: Return type of Hyperf\Utils\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Fluent.php on line 143
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 94

Deprecated: Return type of Hyperf\Utils\Optional::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 94
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 105

Deprecated: Return type of Hyperf\Utils\Optional::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 105
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 116

Deprecated: Return type of Hyperf\Utils\Optional::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 116
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 128

Deprecated: Return type of Hyperf\Utils\Optional::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Optional.php on line 128
PHP Deprecated:  Return type of Hyperf\Utils\Stringable::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Stringable.php on line 799

Deprecated: Return type of Hyperf\Utils\Stringable::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /data/project/vendor/hyperf/utils/src/Stringable.php on line 799

**Comment by brightlycolor** [comment]
Same issue

**Comment by nio-ares** [comment]
me too

**Comment by limingxinleo** [comment]
please use hyperf 3.0
